### ISSUE TITLE
Changing layer doesn' change the thumbnail preview correctly

### ISSUE THREAD

**Issue by axheine** [consbio/Leaflet.Basemaps#12]
Hi,

I use your cool plugin on a little webapp.
I've tested it on firefox with leaflet 1.0.3.

Both on my webapp and on your example y got the bug.
When I switch between layers, the preview doesn't follow. 
There is two captures from your example :
![capture d ecran 2017-02-14 a 16 06 25](https://cloud.githubusercontent.com/assets/6041387/22934539/9cf0bc92-f2cf-11e6-8c25-8b327cbe6b26.png)
![capture d ecran 2017-02-14 a 16 06 41](https://cloud.githubusercontent.com/assets/6041387/22934540/9eb26cf6-f2cf-11e6-9fe4-35b10ce54b25.png)

But, on hover, the gold ring is on the good thumbnail.

Axel HEINE

**Comment by brendan-ward** [comment]
Hi @axheine I'm not sure I follow the issue.  Right now, the preview thumbnail is based on the left-most thumbnail that is not currently selected.  So in this case, the middle layer is selected, and the far left is the preview:

![image](https://cloud.githubusercontent.com/assets/3375604/22949146/0ef2692c-f2b6-11e6-846d-a118282c69f1.png)

![image](https://cloud.githubusercontent.com/assets/3375604/22949155/17d9684c-f2b6-11e6-81aa-3320d7aa0327.png)


When I instead select the far left thumbnail to show on the map, I get the next left-most thumbnail:

![image](https://cloud.githubusercontent.com/assets/3375604/22949194/3a588e16-f2b6-11e6-8954-f65b0f1a4622.png)

![image](https://cloud.githubusercontent.com/assets/3375604/22949198/41e60e92-f2b6-11e6-87f2-eea431cc0429.png)

The orange ring indicates the one currently shown on the map.

I did this because I wanted the thumbnail to indicate a different basemap option, rather than matching the current one showing.  For instance, I don't think this is very helpful:

![image](https://cloud.githubusercontent.com/assets/3375604/22949292/93b99a2c-f2b6-11e6-97eb-861db1f6c1b1.png)


What do you want the thumbnail to show?

**Comment by axheine** [comment]
Hi, 
Thanks for the answer.

Currently the third thumbnail is never shown. 
Why don't try to swith each time to the right and if there is no thumbnail on the right come back to the first one?

**Comment by axheine** [comment]
Works fine with :
`var altIdx = (i+1)%this.options.basemaps.length;`

**Comment by brendan-ward** [comment]
Thanks for the tip.  Resolved by #ddf21194c463191c2404099c96f2ad82414f6a63
