### ISSUE TITLE
Allow to represent each layer with a different tile

### ISSUE THREAD

**Issue by Poldy1705** [consbio/Leaflet.Basemaps#15]
Each basemap is represented using a tile from the underlying tile service. 
It's a global configuration for all defined layers. I think it's better to do this for each Layer separately.

**Comment by brendan-ward** [comment]
@Poldy1705 we'll consider this.  Right now, our particular use case relies on showing alternative basemaps for a given geography, so using the same tile index is important.

Can you give us an example set of basemaps with the tile configuration embedded so that we can see how you would like this to look in the API?

**Comment by Poldy1705** [comment]
var map = new L.map('map').setView([52.027977, 8.908174], 18);
	
		
	var basemaps = [
    L.tileLayer('https://maps.omniscale.net/v2/swl-33d96aa8/style.default/{z}/{x}/{y}.png', {
        attribution: '&copy; 2016 &middot; <a href="https://maps.omniscale.com/">Omniscale</a> ' +
		'&middot; Map data: <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        minZoom: 10,
		maxZoom: 20,
        label: 'OpenStreetMap',  // optional label used for tooltip
		tileX: 2149,  // tile X coordinate
		tileY: 1352,  // tile Y coordinate
		tileZ: 12   // tile zoom level
    }),
	L.tileLayer.wms('https://www.wms.nrw.de/geobasis/wms_nw_dop20?', {
		layers: 'nw_dop20',
		attribution: "Data &copy; SW Lemgo",
		format:'image/png',
		transparent: false,
		detectRetina: true,
		minZoom: 10,
		maxZoom: 22,
		label: 'Luftbilder',
		tileX: 2149,  // tile X coordinate
		tileY: 1352,  // tile Y coordinate
		tileZ: 12   // tile zoom level
	}),
    L.tileLayer.wms('https://qgis-wms.stadtwerke-lemgo.de/qgis/qgis_mapserv.fcgi.exe?map=C:/Apache24/htdocs/QGIS-Web-Client-master/projects/Lemgo_offline/Lemgo_bud_offline.qgs', {
		layers: 'Kommune',
		attribution: "Data &copy; SW Lemgo",
		format:'image/png',
		transparent: false,
		detectRetina: true,
		minZoom: 10,
		maxZoom: 22,
        label: 'Kommune Grundkarte',
		tileX: 2149,  // tile X coordinate
		tileY: 1352,  // tile Y coordinate
		tileZ: 12   // tile zoom level
    }),
	L.tileLayer.wms('https://maps.stadtwerke-lemgo.de/mapproxy/service?', {
		layers: 'Wasser',
		attribution: "Data &copy; SW Lemgo",
		format:'image/png',
		transparent: false,
		detectRetina: true,
		minZoom: 18,
		maxZoom: 22,
		label: 'Wasser',
		tileX: 550256,  // tile X coordinate
		tileY: 346307,  // tile Y coordinate
		tileZ: 20   // tile zoom level
	})
	];

	map.addControl(L.control.basemaps({
    basemaps: basemaps
	}));

**Comment by brendan-ward** [comment]
@Poldy1705 very sorry it took me so long to finish this!

I ended up with going with a slightly different approach than your example, but I think it provides a more general solution to the issue you raised.  Now you can provide whatever `iconURL` for a basemap's icon, instead of passing in arbitrary z, x, y for it to construct for you.
