### ISSUE TITLE
Default Layer for Thumbnail Icon

### ISSUE THREAD

**Issue by Poldy1705** [consbio/Leaflet.Basemaps#16]
Possibility to define a default Layer for the start thumbnail - Icon of the Layerswitcher.

**Comment by brendan-ward** [comment]
@Poldy1705 I don't quite understand: right now there is no icon, only the thumbnails of the basemaps.  That is by design; we want this to give an immediate impression of the basemaps that can be chosen, versus hiding them behind an icon like the standard leaflet layer switcher.

Can you please describe your idea in a bit more detail, or share a rough sketch, or something - so that we can understand you are asking for?

**Comment by Poldy1705** [comment]
Sorry for my undetailed post.

The thumbnails for the basemaps change when you choose one of them. If you have 3 defined basemaps and choose the second thumbnail then the third thumbnail is displayed when the "Layerswitcher" is closed.

I think it is better to define a default thumbnail (maybe a separate thumbnail) for the "Layerswitcher" itself.

**Comment by brendan-ward** [comment]
@Poldy1705 the behavior you describe of showing an alternative tile image when you select a given basemap is by design; we want it to represent an alternative to the basemap currently shown.

You might find one of the other Leaflet layer switcher plugins better meets your needs: http://leafletjs.com/plugins.html#layer-switching-controls
