### ISSUE TITLE
Basemap leaflet control close image

### ISSUE THREAD

**Issue by dd-fadhilah** [consbio/Leaflet.Basemaps#19]
Hi,

It would be nice if the basemap leaflet-control closed image is based on the selected or current displayed basemap on the map. The current working is when the control is closed, the image displays the next (to the right of the list) image of the basemap.

Just a suggestion. BTW thanks for sharing the codes ;)

**Comment by brendan-ward** [comment]
@dd-fadhilah showing an *alternative* basemap in the closed image was by design, to indicate that clicking (if there are only 2 basemaps) or hovering over it will provide a different basemap than what you are currently viewing.  This is the same approach that Google Maps uses.

What do you see is the value of showing a thumbnail of the current basemap within the basemap control when it is closed?  Does it set a different expectation about what you would get from interacting with it?

**Comment by brendan-ward** [comment]
Closed due to lack of activity.
