### ISSUE TITLE
Change a layer basemap after added to map

### ISSUE THREAD

**Issue by JCFMachado** [consbio/Leaflet.Basemaps#24]
Is it possible to change a basemap layer from the list after the control has been initialized and added to the map? I can't seem to find a way to do it. Maybe it could be a useful feature?

**Comment by brendan-ward** [comment]
@JCFMachado Can you please describe your use case a little bit more?

Are you trying to remove an existing basemap option, modify the originating URL for tiles for an existing basemap, or add one or more new basemaps after it is constructed?

**Comment by JCFMachado** [comment]
I'm trying to replace an existing basemap with another (a different tilelayer) after the control is added to the map. 
In the toggle demo, i would need to replace a basemap after map.addControl(...) was called.

**Comment by brendan-ward** [comment]
It looks possible to refactor the contents of the `onAdd` function so that the implementation for constructing thumbnails and event handlers can be called both at startup time and in response to calling a function at some other time.   It's a bit more of a refactor than I have time for right now, but I'd be open to a PR that adds this functionality - I can see it being more broadly useful.

I'd suggest describing the API you want to implement for this before implementing it, if you want to go the route of working up a PR.  That way we can sort out a few of the implementation details prior to doing the majority of the work...

**Comment by JCFMachado** [comment]
That was what I thought, I'm overclocking right now to get our job done atm, but I can probably come back to this later on. As you said, it could probably benefit others. Thanks Brendan for your work.
